### PR TITLE
adding mile convertor to length.py and pound convertor to weight.py

### PR DESCRIPTION
**Pull request by smmnaghibi**
Hi, if the code is OK, i will create the test for it.

### CODE REVIEW

**Comment by pouriya** [comment]
👍🏼 
it's time to provide test and update the documentation.

**Comment by pouriya** [comment]
ping

**Comment by smmnaghibi** [comment]
test has just push to this repo

**Comment by pouriya** [comment]
please resolve the conflict

**Comment by smmnaghibi** [comment]
done

**Comment by pouriya** [comment]
CI has failed!

**Pull request closed without merging**
